# Specifies the version of the Compose file format. This version requires Docker Engine 19.03.0 or above.
version: '3.8'

# Defines the services, networks, or volumes that can be used by the application.
services:
  # Defines the backend service.
  backend:
    build:
      context: ./backend # Specifies the directory containing the Dockerfile as the build context for the backend service.
      dockerfile: Dockerfile # Points to the Dockerfile used for building the backend service.
    ports:
      - "4000:5000" # Maps port 5000 of the container to port 5000 on the host, enabling access to the backend service.
    environment:
      - NODE_ENV=production # Sets an environment variable inside the container to indicate production mode.
    image: ashnahkhalidkhan00210/mongo-crud-backend:latest # Names the image built from the Dockerfile for easier reference.

  # Defines the frontend service.
  frontend:
    build:
      context: ./frontend # Specifies the directory containing the Dockerfile as the build context for the frontend service.
      dockerfile: Dockerfile # Points to the Dockerfile used for building the frontend service.
    ports:
      - "3000:80" # Maps port 80 of the container to port 80 on the host, enabling access to the frontend service.
    environment:
      - NODE_ENV=production # Sets an environment variable inside the container to indicate production mode.
    image: ashnahkhalidkhan00210/mongo-crud-frontend:latest # Names the image built from the Dockerfile for easier reference.
