# Use the official Node.js 16 as a parent image
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /app/backend

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Bundle app source
COPY . .

# Your app binds to port 3001, make sure you use the same port everywhere
EXPOSE 5000

# Define the command to run your app
CMD [ "npm","start" ]
