apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        # image: moatas19m/mongo-crud-backend:latest
        image: ashnahkhalidkhan00210/mongo-crud-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            # cpu: "500m"
            # memory: "2Gi"
            cpu: "250m"  # Reduced from 500m
            memory: "1Gi"
          # limits:
          #   cpu: "500m"
          #   memory: "2Gi"
      imagePullSecrets:
      - name: myregistrykey